In [10]:
import numpy as np

## Cholesky Factorization

### $P_{77}$ Exa. 4.6:
### $A=\left[\begin{matrix}4 & -2 & 4\\-2 & 5 & -4\\4 & -4 & 14\end{matrix}\right]$

In [11]:
A = np.array([[4, -2, 4], [-2, 5, -4], [4, -4, 14]])
A

array([[ 4, -2,  4],
       [-2,  5, -4],
       [ 4, -4, 14]])

### From Scratch

In [12]:
def cholesky_factorization(A):
    n = len(A)
    L = np.zeros_like(A)
    for i in range(n):
        for j in range(i+1):
            if i == j:
                val = A[i,i] - np.sum(L[i,:i]**2)
                if val < 0:
                    return 0.0
                L[i,i] = np.sqrt(val)
            else:
                L[i,j] = (A[i,j] - np.sum(L[i,:j]*L[j,:j])) / L[j,j]
                
    return L

In [13]:
L = cholesky_factorization(A)
L

array([[ 2,  0,  0],
       [-1,  2,  0],
       [ 2, -1,  3]])

### Using `Numpy`

In [14]:
L = np.linalg.cholesky(A)
L

array([[ 2.,  0.,  0.],
       [-1.,  2.,  0.],
       [ 2., -1.,  3.]])

In [15]:
np.allclose(L @ L.T, A)

True

## Using Cholesky for Solving $Ax=b$
### $\left[\begin{matrix}2 & -2 & 3\\-2 & 5 & 4\\ -3 & 4 & 5\end{matrix}\right] \left [ \begin{matrix} x_1 \\ x_2 \\ x_3\end{matrix}\right] =\left[\begin{matrix}7\\-12\\-12\end{matrix}\right]$

### From Scratch

In [97]:
def forward_substitution(L, b):
    n = len(L)
    y = np.zeros(n)
    y[0] = b[0] / L[0][0]
    for k in range(1, n):
        y[k] = (b[k] - L[k, 0:k] @ y[0:k]) / L[k][k]
    return y

In [98]:
def back_substitution(A, b):
    n = len(A)
    x = np.zeros(n)
    G = np.c_[A, b]
    x[n-1] = G[n-1, n] / G[n-1, n-1]
    
    for k in range(n-1, -1, -1):
        x[k] = (G[k, n] - np.dot(G[k, k+1:n], x[k+1:n])) / G[k, k]
    return x

In [138]:
A = np.array([[2, -2, 3], [-2, 5, 4], [-3, 4, 5]])
b = np.array([7, -12, -12])

In [140]:
y = forward_substitution(L, A.T @ b)
x = back_substitution(L.T, y)
x

array([ 1.74418605, -1.72093023,  0.02325581])

### Using `Numpy`

In [142]:
np.linalg.solve(A, b)

array([ 1.74418605, -1.72093023,  0.02325581])