In [1]:
import numpy as np

## Householder QR

### P101 Exa. 5.3, 5.4 
$A=\left[\begin{matrix}2 & -1 & 5\\2 & 1 & 2\\1 & 0 & -2\end{matrix}\right]$

### From Scratch

In [2]:
def householder_qr(A):
    n = len(A)
    Q = np.identity(n)
    R = A
    I = np.identity(n)
    for k in range(n - 1):
        a = R[:, k]
        v = a - np.linalg.norm(a) * I[:, k]
        v = v.reshape(-1, 1)
        Hv = I - 2 * (v @ v.T) /  (v.T @ v)
        R = Hv @ R
        Q = Q @ Hv.T
        
    return Q, R

In [3]:
A = np.array([[2, -1, 5], [2, 1, 2], [1, 0, -2]])
Q, R = householder_qr(A)
print("Q:\n {}".format(Q))
print("R:\n {}".format(R))

Q:
 [[ 6.66666667e-01 -7.07106781e-01 -2.35702260e-01]
 [ 6.66666667e-01  7.07106781e-01 -2.35702260e-01]
 [ 3.33333333e-01 -5.55111512e-17  9.42809042e-01]]
R:
 [[ 3.00000000e+00 -1.84889275e-32  4.00000000e+00]
 [-3.92523115e-16  1.41421356e+00 -2.12132034e+00]
 [-9.75530386e-17 -1.11022302e-16 -3.53553391e+00]]


In [4]:
np.allclose(A, Q @ R)

True

### Using `Numpy`

In [5]:
Q, R = np.linalg.qr(A)
print("Q:\n {}".format(Q))
print("R:\n {}".format(R))

Q:
 [[-6.66666667e-01  7.07106781e-01 -2.35702260e-01]
 [-6.66666667e-01 -7.07106781e-01 -2.35702260e-01]
 [-3.33333333e-01  2.77555756e-17  9.42809042e-01]]
R:
 [[-3.          0.         -4.        ]
 [ 0.         -1.41421356  2.12132034]
 [ 0.          0.         -3.53553391]]
