In [13]:
import numpy as np

## QR Factorization

### $P_{97}$ Exa. 5.2: 
$A=\left[\begin{matrix}1 & 1 & 1\\0 & 1 & 1\\0 & 1 & 0\end{matrix}\right]$

### From Scratch

In [14]:
def ratio(v1, v2):
    return v2.dot(v1) / v1.dot(v1)

In [15]:
def projection(v1, v2):
    return ratio(v1, v2) * v1

In [16]:
def gramm_schmidt_normalized(x):
    x = x.T
    n = len(x)
    # Put orthogonal ones into a list
    v_lst = []
    v_lst.append(x[0] / np.linalg.norm(x[0]))
    
    for k in range(1, n):
        sum_prj = 0
        for v in v_lst:
            sum_prj += projection(v, x[k]) # Projecting onto orthonormal basis
        r = x[k] - sum_prj # Residual is orthogonal to current basis
        r_nor = r / np.linalg.norm(r)
        v_lst.append(r_nor)
    return v_lst    

In [17]:
A = np.array([[1, 1, 1], [0, 1, 1], [0, 1, 0]]).astype(float)
v_orths_normed = gramm_schmidt_normalized(A)
v_orths_normed

[array([1., 0., 0.]),
 array([0.        , 0.70710678, 0.70710678]),
 array([ 0.        ,  0.70710678, -0.70710678])]

In [18]:
Q = np.array([v_orths_normed[0], v_orths_normed[1], v_orths_normed[2]])
print("Q: {}\n".format(Q))

Q: [[ 1.          0.          0.        ]
 [ 0.          0.70710678  0.70710678]
 [ 0.          0.70710678 -0.70710678]]



In [19]:
R = Q.T @ A
print("R: {}".format(R))

R: [[1.         1.         1.        ]
 [0.         1.41421356 0.70710678]
 [0.         0.         0.70710678]]


In [20]:
np.allclose(A, Q.T @ R)

True

### Using `Numpy`

In [26]:
A = np.array([[1, 1, 1], [0, 1, 1], [0, 1, 0]]) 
Q, R = np.linalg.qr(A)
print("Q:\n {}".format(Q))
print("R:\n {}".format(R))

Q:
 [[ 1.          0.          0.        ]
 [ 0.         -0.70710678 -0.70710678]
 [ 0.         -0.70710678  0.70710678]]
R:
 [[ 1.          1.          1.        ]
 [ 0.         -1.41421356 -0.70710678]
 [ 0.          0.         -0.70710678]]


## Using QR for Solving $Ax=b$

### $\left[\begin{matrix}2 & 3\\5 & 4\end{matrix}\right] \left [ \begin{matrix} x_1 \\ x_2 \end{matrix}\right] =\left[\begin{matrix}4\\3\end{matrix}\right]$

In [27]:
A = np.array([[2, 3], [5, 4]])
b = np.array([4, 3])

In [28]:
Q, R = scipy.linalg.qr(A)

In [29]:
def back_substitution(A, b):
    n = len(A)
    x = np.zeros(n)
    G = np.c_[A,b]
    x[n-1] = G[n-1, n] / G[n-1, n-1]
    
    for k in range(n-1, -1, -1):
        x[k] = (G[k, n] - G[k, k+1:n] @ x[k+1:n]) / G[k, k]
    return x

In [30]:
back_substitution(R, Q.T @ b)

array([-1.,  2.])

In [31]:
np.linalg.solve(A, b)

array([-1.,  2.])