In [1]:
import numpy as np

## Underdetermined

### Using SVD

In [2]:
A = np.array([[1, 2, 3], [4, 5, 32]])
b = np.array([[7], [8]])

In [13]:
u, s, vh = np.linalg.svd(A)
s = np.r_[np.diag(1 / s), np.zeros((1, 2))]
x = vh.T @ s @ u.T @ b
x

array([[ 1.40320285],
       [ 3.5088968 ],
       [-0.47366548]])

### Using Tikhonov Regularization

In [7]:
I = np.identity(3)
alpha = 0.0001
x2 = np.linalg.solve((A.T @ A - alpha * I) , A.T @ b)
x2

array([[ 1.40325534],
       [ 3.50902962],
       [-0.47369353]])

In [11]:
x3 = np.linalg.solve(A.T @ A, A.T @ b)
x3

array([[-8.        ],
       [ 7.34693878],
       [ 0.10204082]])

In [15]:
np.linalg.norm(x2) < np.linalg.norm(x3)

True

## Fully Determined

In [212]:
A = np.array([[2, 3], [5, 4]])
b = np.array([1, 2])

In [213]:
u, s, vh = np.linalg.svd(A)
x = vh.T @ np.diag(1 / s) @ u.T @ b
x

array([0.28571429, 0.14285714])

In [214]:
np.linalg.solve(A, b)

array([0.28571429, 0.14285714])

## Overdetermined

In [79]:
A = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[10], [11], [12]])

In [89]:
u, s, vh = np.linalg.svd(A)
s = np.c_[np.diag(1 / s), np.zeros((2, 1))]

In [90]:
x = vh.T @ s @ u.T @ b
x

array([[-9. ],
       [ 9.5]])

In [91]:
np.linalg.solve(A.T @ A, A.T @ b)

array([[-9. ],
       [ 9.5]])