In [1]:
import numpy as np
import scipy.linalg

### $A=\left [ \begin{matrix} 1 & 2 \\  3 & 4 \\ 5 & 6 \end{matrix}\right]$

In [2]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

## Computing with Eigenvectors

### Methods 1

In [3]:
eigvals, eigvshs = np.linalg.eig(A.T @ A)
V = eigvshs[:,::-1]
print("V:\n {}".format(V))

V:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [4]:
U = A @ V @ np.diag(1 / np.sqrt(eigvals[::-1]))
U

array([[-0.2298477 ,  0.88346102],
       [-0.52474482,  0.24078249],
       [-0.81964194, -0.40189603]])

In [5]:
S = np.diag(np.sqrt(eigvals[::-1]))
S

array([[9.52551809, 0.        ],
       [0.        , 0.51430058]])

In [6]:
np.allclose(A, U @ S @ V.T)

True

### Methods 2

In [7]:
T = A @ V
U = []
for i in range(T.shape[1]):
    normalized_col = T[:, i] / np.linalg.norm(T[:, i])
    U.append(normalized_col)
U = np.array(U).T
U

array([[-0.2298477 ,  0.88346102],
       [-0.52474482,  0.24078249],
       [-0.81964194, -0.40189603]])

In [8]:
S = np.diag(np.sqrt(eigvals[::-1]))
S

array([[9.52551809, 0.        ],
       [0.        , 0.51430058]])

In [9]:
np.allclose(A, U @ S @ V.T)

True

### Method 3

In [10]:
_, eigvshs2 = np.linalg.eig(A @ A.T)
U = eigvshs2
print("U:\n {}".format(U))

U:
 [[-0.2298477  -0.88346102  0.40824829]
 [-0.52474482 -0.24078249 -0.81649658]
 [-0.81964194  0.40189603  0.40824829]]


In [11]:
S = np.vstack([np.diag(np.sqrt(eigvals[::-1])), np.zeros(len(V))])
print("S:\n {}".format(S))

S:
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


In [21]:
np.allclose(A, U @ S @ V.T)

True

### Using `Numpy`

In [22]:
U, S, V_T = np.linalg.svd(A)
S = np.vstack([np.diag(S), np.zeros(len(V))])
print("U:\n {}".format(U))
print("S:\n {}".format(S))
print("V:\n {}".format(V_T.T))

U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S:
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]
V:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [23]:
U_AV_normalized = U[:, :-1]
U_AV_normalized

array([[-0.2298477 ,  0.88346102],
       [-0.52474482,  0.24078249],
       [-0.81964194, -0.40189603]])

In [24]:
np.allclose(A, U @ S @ V.T)

True