In [2]:
import numpy as np

### $A = QΛQ^{-1}$

In [54]:
#A = np.array([[1.1, 1.2748], [0.11767, 1.150]])
A = np.array([[4, -2, 4], [-2, 5, -4], [4, -4, 14]])
A

array([[ 4, -2,  4],
       [-2,  5, -4],
       [ 4, -4, 14]])

In [55]:
eiglvals, eigvshs = np.linalg.eig(A)
eiglvals, eigvshs

(array([17.04078643,  2.32558662,  3.63362695]),
 array([[ 0.32323917, -0.8892936 , -0.32353258],
        [-0.34626061, -0.42932437,  0.83413678],
        [ 0.88069293,  0.15759909,  0.4467018 ]]))

In [56]:
eigvshs

array([[ 0.32323917, -0.8892936 , -0.32353258],
       [-0.34626061, -0.42932437,  0.83413678],
       [ 0.88069293,  0.15759909,  0.4467018 ]])

In [57]:
D = np.diag(eiglvals)
Q = eigvshs
print("D:\n {}".format(D))
print("Q:\n {}".format(Q))

D:
 [[17.04078643  0.          0.        ]
 [ 0.          2.32558662  0.        ]
 [ 0.          0.          3.63362695]]
Q:
 [[ 0.32323917 -0.8892936  -0.32353258]
 [-0.34626061 -0.42932437  0.83413678]
 [ 0.88069293  0.15759909  0.4467018 ]]


In [58]:
np.allclose(Q @ D @ np.linalg.inv(Q), A)

True

In [62]:
np.allclose(Q @ D @ Q.T, A) # for symmetric positive matix

True