In [2]:
import numpy as np
import scipy.linalg

In [3]:
#A = np.array([[1.1, 1.2748], [0.11767, 1.150]])
A = np.array([[4, -2, 4], [-2, 5, -4], [4, -4, 14]])
A

array([[ 4, -2,  4],
       [-2,  5, -4],
       [ 4, -4, 14]])

##  Inverse Interaction

### From Scratch

#### Without  LU

In [4]:
def inverse_iteration(A, iter_max=100):
    n = len(A)
    v = np.ones(n)
    v_lst = []
    v_lst.append(v)
    for i in range(iter_max):
        w = np.linalg.inv(A) @ v_lst[i]
        v_lst.append(w / np.linalg.norm(w))
        if v_lst[i + 1].T @ v_lst[i] < 0.0:
            v_lst[i + 1]  = -v_lst[i + 1] 
        if np.linalg.norm(v_lst[i + 1] - v_lst[i]) < 1e-6: break
    return v_lst

In [5]:
eigenvec_lst = inverse_iteration(A)
eigenvec = eigenvec_lst[-1]
eigenvec

array([ 0.88929319,  0.42932543, -0.15759852])

In [6]:
Z = A @ eigenvec
lamb = np.linalg.norm(Z)
lamb

2.3255866228682707

#### With LU

In [7]:
def back_substitution(A, b):
    n = len(A)
    x = np.zeros(n)
    G = np.c_[A, b]
    x[n-1] = G[n-1, n] / G[n-1, n-1]
    
    for k in range(n-1, -1, -1):
        x[k] = (G[k, n] - np.dot(G[k, k+1:n], x[k+1:n])) / G[k, k]
    return x

In [15]:
def inverse_iteration_lu(A, iter_max=100):
    n = len(A)
    v = np.ones(n) - 2
    v_lst = []
    v_lst.append(v)
    L, U = scipy.linalg.lu(A, permute_l=True)
    for i in range(iter_max):
        y = np.linalg.solve(L, v_lst[i])
        w = back_substitution(U, y)
        v_lst.append(w / np.linalg.norm(w))
        if v_lst[i + 1].T @ v_lst[i] < 0.0:
            v_lst[i + 1]  = -v_lst[i + 1] 
        if np.linalg.norm(v_lst[i + 1] - v_lst[i]) < 1e-6: 
            print("The number of iteration: {}".format(i + 1))
            break
    return v_lst

In [16]:
eigenvec_lst = inverse_iteration_lu(A)

The number of iteration: 30


In [17]:
eigenvec = eigenvec_lst[-1]
eigenvec

array([-0.88929319, -0.42932543,  0.15759852])

In [18]:
Z = A @ eigenvec
lamb = np.linalg.norm(Z)
lamb

2.3255866228682702

### Using `Nympy`

In [19]:
eig_vals, eig_vecs = np.linalg.eig(A)
eig_vals.min()

In [14]:
eig_vecs[:, np.argmin(eig_vals)]

array([-0.8892936 , -0.42932437,  0.15759909])