In [23]:
import numpy as np

In [30]:
#A = np.array([[1.1, 1.2748], [0.11767, 1.150]])
A = np.array([[4, -2, 4], [-2, 5, -4], [4, -4, 14]])
A

array([[ 4, -2,  4],
       [-2,  5, -4],
       [ 4, -4, 14]])

## Krylov Subspace Methods

### From Scratch

In [34]:
def ratio(v1, v2):
    return v2.dot(v1) / v1.dot(v1)

In [35]:
def projection(v1, v2):
    return ratio(v1, v2) * v1

In [39]:
def krylov_subspace_methods(A, iter_max=100):
    n = len(A)
    q0 = np.random.ranf(n)
    q0 = q0 / np.linalg.norm(q0)
    q = []
    q.append(q0)
    for k in range(iter_max):
        ak = A @ q[k]
        sum_prj = 0
        for h in range(k):
            sum_prj += projection(ak, q[h])
        bk = ak - sum_prj
        q.append(bk / np.linalg.norm(bk))
        if (q[k+1] @ q[k]) < 0.0:
            q[k+1] = -q[k+1]
        if np.linalg.norm(q[k+1] - q[k]) < 1e-6: 
            print("The number of iterations: {}".format(k + 1))
            break
    return q

In [40]:
eigenvecs_lst = krylov_subspace_methods(A)
eigenvec = eigenvecs_lst[-1]
eigenvec

The number of iterations: 11


array([ 0.32323911, -0.34626045,  0.88069301])

### Using `Numpy`

In [43]:
eig_vals, eig_vecs = np.linalg.eig(A)
eig_vals.min()

2.3255866228655884

In [45]:
eig_vecs[:, np.argmax(eig_vals)]

array([ 0.32323917, -0.34626061,  0.88069293])