In [2]:
import numpy as np

In [16]:
A = np.array([[1.1, 1.2748], [0.11767, 1.150]])
# A = np.array([[-2, 1, 2], 
#               [ 5, 3, -7],
#               [ 9, -5, 1]])
A

array([[1.1    , 1.2748 ],
       [0.11767, 1.15   ]])

## Projected Iteration

### From Scratch

In [17]:
def ratio(v1, v2):
    return v2.dot(v1) / v1.dot(v1)

In [18]:
def projection(v1, v2):
    return ratio(v1, v2) * v1

In [24]:
def projected_iteration(A, iter_max=100):
    n = len(A)
    eigen_vecs = np.ones((n, n))
    eigen_vals = np.ones((n, 1))
    for l in range(n):
        v0 = np.ones(n)
        v_lst = []
        v_lst.append(v0)
        for p in range(iter_max):
            sum_prj = 0
            for q in range(l):
                sum_prj += projection(eigen_vecs[:, q], v_lst[p]) 
    
            u = v_lst[p] - sum_prj
            w = A @ u
            v_lst.append(w / np.linalg.norm(w))
            if (v_lst[p+1] @ v_lst[p]) < 0.0:
                sign = -1
                v_lst[p+1] = -v_lst[p+1]
            else:
                sign = 1
            if np.linalg.norm(v_lst[p+1] - v_lst[p]) < 1e-6: 
                print("The number of eigenvector{} iteration: {}".format(l+ 1,  
                                                                         p + 1))
                break
        eigen_vecs[:, l] = -sign * v_lst[-1]
        Z = A @ eigen_vecs[:, l]
        eigen_vals[l] = sign * np.linalg.norm(Z)
    return eigen_vals, eigen_vecs

In [25]:
eigen_vals, eigen_vecs = projected_iteration(A)
print("The eigenvalues:\n {}".format(eigen_vals.T)) 
print("The eigenvectors:\n {}".format(eigen_vecs))

The number of eigenvector1 iteration: 18
The number of eigenvector2 iteration: 2
The eigenvalues:
 [[1.51311253 1.9386801 ]]
The eigenvectors:
 [[-0.95129636 -0.63681289]
 [-0.30827785 -0.77101838]]


### Using `Numpy`

In [26]:
np.linalg.eig(A)

(array([0.73688827, 1.51311173]), array([[-0.9617462 , -0.95129657],
        [ 0.27394205, -0.3082772 ]]))