In [2]:
import numpy as np

In [3]:
A = np.array([[1.1, 1.2748], [0.11767, 1.150]])
# A = np.array([[-2, 1, 2], 
#               [ 5, 3, -7],
#               [ 9, -5, 1]])
A

array([[1.1    , 1.2748 ],
       [0.11767, 1.15   ]])

## QR Iteration

### From Scratch

In [4]:
def QR_Iteration(A, iter_max=100):
    n = len(A)
    v = np.ones(n)
    eigenvals_lst = []
    for i in range(iter_max):
        Q, R = np.linalg.qr(A)
        A = R @ Q
        eigenvals_lst.append(np.diag(A))
        if i > 0 and np.linalg.norm(eigenvals_lst[i] - eigenvals_lst[i-1]) < 1e-10:
            print("The number of iteration: {}".format(i + 1))
            break
    return eigenvals_lst

In [5]:
eigenvals_lst = QR_Iteration(A)
eigenvals = eigenvals_lst[-1]
eigenvals

The number of iteration: 33


array([1.51311173, 0.73688827])

### Using `Numpy`

In [6]:
np.linalg.eigvals(A)

array([0.73688827, 1.51311173])