In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
A = np.array([[1.1, 1.2748], [0.11767, 1.150]])
A = np.array([[-2, 1, 2], 
              [ 5, 3, -7],
              [ 9, -5, 1]])
A

array([[-2,  1,  2],
       [ 5,  3, -7],
       [ 9, -5,  1]])

## Rayleigh Quotient Iteration

### From Scratch

In [12]:
def rayleigh_quotient_iteration(A, sigma, iter_max=100):
    n = len(A)
    v = np.ones((n, 1)) -2
    I = np.identity(n)
    v_lst = []
    v_lst.append(v)
    for i in range(iter_max):
        w = np.linalg.inv(A - sigma * I) @ v_lst[i]
        v_lst.append(w / np.linalg.norm(w))
        sigma = (v_lst[i+1].T @ A @ v_lst[i+1]) / np.linalg.norm(v_lst[i+1])**2
        if np.linalg.norm(v_lst[i+1] - v_lst[i]) < 1e-6:
            print("The number of iteration: {}".format(i + 1))
            break
    return v_lst

In [13]:
eigen_vecs = rayleigh_quotient_iteration(A, 0)
eigen_vec = eigen_vecs[-1]
eigen_vec

The number of iteration: 5


array([[-0.45694634],
       [-0.75708239],
       [-0.46693287]])

In [14]:
Z = A @ eigen_vec
np.linalg.norm(Z)

1.7005398479242304

In [15]:
eigen_vecs = rayleigh_quotient_iteration(A, 5)
eigen_vec = eigen_vecs[-1]
eigen_vec

The number of iteration: 5


array([[-0.45694634],
       [-0.75708239],
       [-0.46693287]])

In [16]:
Z = A @ eigen_vec
np.linalg.norm(Z)

1.7005398479242304

### Using `Numpy`

In [17]:
eigen_vals, eigen_vecs = np.linalg.eig(A)

In [18]:
eigen_vals

array([-7.82094512,  1.70053985,  8.12040527])

In [19]:
eigen_vecs

array([[ 0.34840643, -0.45694634,  0.04217561],
       [-0.61729331, -0.75708239, -0.79180302],
       [-0.7053807 , -0.46693287,  0.60931863]])